version: '2.1'
services:
  nginx:
    build: docker/nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/logs/:/var/log/nginx
      - /jobs:/var/www/jobs
    healthcheck:
            test: "exit 0"
  php:
    build: docker/php
    restart: always
    volumes:
      - /jobs:/var/www/jobs
  db:
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobs
    healthcheck:
            test: "exit 0"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  composer:
    image: composer:1.7.2
    volumes:
      - "/jobs:/app"
    command: install
  migration:
    build: docker/migration
    hostname: migration
    volumes:
      - /jobs:/var/www/jobs
    depends_on:
      db:
         condition: service_healthy
      nginx:
         condition: service_healthy
